"""import job constraint warnings

Revision ID: 3556590ec176
Revises: 99e55968efd5
Create Date: 2026-09-10 11:16:14.395706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3556590ec176'
down_revision: Union[str, None] = '99e55968efd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'import_jobs',
        sa.Column(
            'warnings', postgresql.JSONB(astext_type=sa.Text()),
            nullable=False, server_default='[]',
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'warnings')
    # ### end Alembic commands ###
