"""workspace default access

Revision ID: 38d2ab53507d
Revises: af68ea6f9981
Create Date: 2026-09-09 17:53:09.264399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38d2ab53507d'
down_revision: Union[str, None] = 'af68ea6f9981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('default_can_read', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workspaces', sa.Column('default_can_create', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workspaces', sa.Column('default_can_modify', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workspaces', sa.Column('default_can_delete', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workspaces', sa.Column('default_can_read_tickets', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workspaces', sa.Column('default_can_create_tickets', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workspaces', sa.Column('default_can_modify_tickets', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workspaces', sa.Column('default_can_delete_tickets', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'default_can_delete_tickets')
    op.drop_column('workspaces', 'default_can_modify_tickets')
    op.drop_column('workspaces', 'default_can_create_tickets')
    op.drop_column('workspaces', 'default_can_read_tickets')
    op.drop_column('workspaces', 'default_can_delete')
    op.drop_column('workspaces', 'default_can_modify')
    op.drop_column('workspaces', 'default_can_create')
    op.drop_column('workspaces', 'default_can_read')
    # ### end Alembic commands ###
