"""initial

Revision ID: 66725fb88e38
Revises: 
Create Date: 2026-09-04 08:33:51.859252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66725fb88e38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_workspace_id'), 'api_tokens', ['workspace_id'], unique=False)
    op.create_table('global_values',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=False),
    sa.Column('multi_value', sa.Boolean(), nullable=False),
    sa.Column('min_cardinality', sa.Integer(), nullable=True),
    sa.Column('max_cardinality', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('egu', sa.String(), nullable=True),
    sa.Column('allowed_egu_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_global_values_workspace_id'), 'global_values', ['workspace_id'], unique=False)
    op.create_table('schemas',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_concrete', sa.Boolean(), nullable=False),
    sa.Column('parent_schema_uid', sa.String(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_schema_uid'], ['schemas.uid'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_schemas_workspace_id'), 'schemas', ['workspace_id'], unique=False)
    op.create_table('assets',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('schema_uid', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('avatar_icon_uid', sa.String(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inbound_relations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('outbound_relations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schema_uid'], ['schemas.uid'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_assets_key'), 'assets', ['key'], unique=True)
    op.create_index(op.f('ix_assets_schema_uid'), 'assets', ['schema_uid'], unique=False)
    op.create_index(op.f('ix_assets_workspace_id'), 'assets', ['workspace_id'], unique=False)
    op.create_table('asset_comments',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asset_uid', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('backend_id', sa.String(), nullable=True),
    sa.Column('backend_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['assets.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_asset_comments_asset_uid'), 'asset_comments', ['asset_uid'], unique=False)
    op.create_table('asset_history',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asset_uid', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('backend_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['assets.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_asset_history_asset_uid'), 'asset_history', ['asset_uid'], unique=False)
    op.create_table('asset_labels',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asset_uid', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['assets.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_asset_labels_asset_uid'), 'asset_labels', ['asset_uid'], unique=False)
    op.create_table('asset_tickets',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asset_uid', sa.String(), nullable=False),
    sa.Column('ticket_key', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('backend_id', sa.String(), nullable=True),
    sa.Column('backend_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['assets.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_asset_tickets_asset_uid'), 'asset_tickets', ['asset_uid'], unique=False)
    op.create_table('attachments',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asset_uid', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['assets.uid'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_attachments_asset_uid'), 'attachments', ['asset_uid'], unique=False)
    op.create_index(op.f('ix_attachments_workspace_id'), 'attachments', ['workspace_id'], unique=False)
    op.create_table('issues',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('asset_uid', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_uid'], ['assets.uid'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_issues_asset_uid'), 'issues', ['asset_uid'], unique=False)
    op.create_index(op.f('ix_issues_workspace_id'), 'issues', ['workspace_id'], unique=False)
    op.create_table('relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_asset_uid', sa.String(), nullable=False),
    sa.Column('to_asset_uid', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_asset_uid'], ['assets.uid'], ),
    sa.ForeignKeyConstraint(['to_asset_uid'], ['assets.uid'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relations_from_asset_uid'), 'relations', ['from_asset_uid'], unique=False)
    op.create_index(op.f('ix_relations_to_asset_uid'), 'relations', ['to_asset_uid'], unique=False)
    op.create_index(op.f('ix_relations_workspace_id'), 'relations', ['workspace_id'], unique=False)
    op.create_table('issue_comments',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('issue_uid', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_uid'], ['issues.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_issue_comments_issue_uid'), 'issue_comments', ['issue_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_comments_issue_uid'), table_name='issue_comments')
    op.drop_table('issue_comments')
    op.drop_index(op.f('ix_relations_workspace_id'), table_name='relations')
    op.drop_index(op.f('ix_relations_to_asset_uid'), table_name='relations')
    op.drop_index(op.f('ix_relations_from_asset_uid'), table_name='relations')
    op.drop_table('relations')
    op.drop_index(op.f('ix_issues_workspace_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_asset_uid'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_attachments_workspace_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_asset_uid'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_asset_tickets_asset_uid'), table_name='asset_tickets')
    op.drop_table('asset_tickets')
    op.drop_index(op.f('ix_asset_labels_asset_uid'), table_name='asset_labels')
    op.drop_table('asset_labels')
    op.drop_index(op.f('ix_asset_history_asset_uid'), table_name='asset_history')
    op.drop_table('asset_history')
    op.drop_index(op.f('ix_asset_comments_asset_uid'), table_name='asset_comments')
    op.drop_table('asset_comments')
    op.drop_index(op.f('ix_assets_workspace_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_schema_uid'), table_name='assets')
    op.drop_index(op.f('ix_assets_key'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_schemas_workspace_id'), table_name='schemas')
    op.drop_table('schemas')
    op.drop_index(op.f('ix_global_values_workspace_id'), table_name='global_values')
    op.drop_table('global_values')
    op.drop_index(op.f('ix_api_tokens_workspace_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
