"""ticket types: issue schema_uid/attributes, schema applies_to

Revision ID: 6f00386a82e4
Revises: 38d2ab53507d
Create Date: 2026-09-10 00:14:26.397573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6f00386a82e4'
down_revision: Union[str, None] = '38d2ab53507d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('schema_uid', sa.String(), nullable=True))
    op.add_column(
        'issues',
        sa.Column(
            'attributes', postgresql.JSONB(astext_type=sa.Text()),
            nullable=False, server_default='{}',
        ),
    )
    op.create_index(op.f('ix_issues_schema_uid'), 'issues', ['schema_uid'], unique=False)
    op.create_foreign_key(None, 'issues', 'schemas', ['schema_uid'], ['uid'])
    op.add_column(
        'schemas',
        sa.Column('applies_to', sa.String(), nullable=False, server_default='objects'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemas', 'applies_to')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_index(op.f('ix_issues_schema_uid'), table_name='issues')
    op.drop_column('issues', 'attributes')
    op.drop_column('issues', 'schema_uid')
    # ### end Alembic commands ###
