"""cascade delete issue comments

Revision ID: 6fff0d69cc5a
Revises: dc1275bd1b00
Create Date: 2026-09-04 12:02:28.164840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6fff0d69cc5a'
down_revision: Union[str, None] = 'dc1275bd1b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('issue_comments_issue_uid_fkey', 'issue_comments', type_='foreignkey')
    op.create_foreign_key(None, 'issue_comments', 'issues', ['issue_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue_comments', type_='foreignkey')
    op.create_foreign_key('issue_comments_issue_uid_fkey', 'issue_comments', 'issues', ['issue_uid'], ['uid'])
    # ### end Alembic commands ###
