"""ticket-specific permissions

Revision ID: af68ea6f9981
Revises: 524959067d70
Create Date: 2026-09-09 17:34:19.868684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af68ea6f9981'
down_revision: Union[str, None] = '524959067d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'memberships',
        sa.Column('can_read_tickets', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        'memberships',
        sa.Column('can_create_tickets', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'memberships',
        sa.Column('can_modify_tickets', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'memberships',
        sa.Column('can_delete_tickets', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'can_delete_tickets')
    op.drop_column('memberships', 'can_modify_tickets')
    op.drop_column('memberships', 'can_create_tickets')
    op.drop_column('memberships', 'can_read_tickets')
    # ### end Alembic commands ###
