"""schema icons and nullable attachment asset

Revision ID: b8a47f0d6be1
Revises: 6fff0d69cc5a
Create Date: 2026-09-04 13:00:31.848611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8a47f0d6be1'
down_revision: Union[str, None] = '6fff0d69cc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'asset_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('schemas', sa.Column('icon_attachment_uid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemas', 'icon_attachment_uid')
    op.alter_column('attachments', 'asset_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
