"""cascade delete asset dependents

Revision ID: dc1275bd1b00
Revises: 66725fb88e38
Create Date: 2026-09-04 10:10:43.939785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc1275bd1b00'
down_revision: Union[str, None] = '66725fb88e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_comments_asset_uid_fkey', 'asset_comments', type_='foreignkey')
    op.create_foreign_key(None, 'asset_comments', 'assets', ['asset_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('asset_history_asset_uid_fkey', 'asset_history', type_='foreignkey')
    op.create_foreign_key(None, 'asset_history', 'assets', ['asset_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('asset_labels_asset_uid_fkey', 'asset_labels', type_='foreignkey')
    op.create_foreign_key(None, 'asset_labels', 'assets', ['asset_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('asset_tickets_asset_uid_fkey', 'asset_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'asset_tickets', 'assets', ['asset_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('attachments_asset_uid_fkey', 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'assets', ['asset_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint('relations_to_asset_uid_fkey', 'relations', type_='foreignkey')
    op.drop_constraint('relations_from_asset_uid_fkey', 'relations', type_='foreignkey')
    op.create_foreign_key(None, 'relations', 'assets', ['from_asset_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relations', 'assets', ['to_asset_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.create_foreign_key('relations_from_asset_uid_fkey', 'relations', 'assets', ['from_asset_uid'], ['uid'])
    op.create_foreign_key('relations_to_asset_uid_fkey', 'relations', 'assets', ['to_asset_uid'], ['uid'])
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key('attachments_asset_uid_fkey', 'attachments', 'assets', ['asset_uid'], ['uid'])
    op.drop_constraint(None, 'asset_tickets', type_='foreignkey')
    op.create_foreign_key('asset_tickets_asset_uid_fkey', 'asset_tickets', 'assets', ['asset_uid'], ['uid'])
    op.drop_constraint(None, 'asset_labels', type_='foreignkey')
    op.create_foreign_key('asset_labels_asset_uid_fkey', 'asset_labels', 'assets', ['asset_uid'], ['uid'])
    op.drop_constraint(None, 'asset_history', type_='foreignkey')
    op.create_foreign_key('asset_history_asset_uid_fkey', 'asset_history', 'assets', ['asset_uid'], ['uid'])
    op.drop_constraint(None, 'asset_comments', type_='foreignkey')
    op.create_foreign_key('asset_comments_asset_uid_fkey', 'asset_comments', 'assets', ['asset_uid'], ['uid'])
    # ### end Alembic commands ###
